name: release

on:
  push:
    tags:
      - "**"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'

      - name: prepare deps
        run: sudo apt-get install ruby-dev build-essential && sudo gem i fpm -f

      - name: package
        run: ./build.sh

      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref_name }} /tmp/gh-ost-release/*.tar.gz
